### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by leafac** [octokit/plugin-retry.js#30]
[Probot](https://github.com/probot/probot/tree/master/src/%40types/%40octokit/plugin-retry) already includes the definitions. We could just include them here and publish them with the package.

**Comment by gr2m** [comment]
Yeah why not :) Would you like to send a pull request?

**Comment by leafac** [comment]
I’ll give it (and https://github.com/octokit/plugin-throttling.js/issues/113) a try in the near future.

**Comment by gr2m** [comment]
I'll take this one and https://github.com/octokit/plugin-throttling.js/issues/113, it's the last two plugins that have not been moved to TypeScript and it's becoming a blocker. I'm sorry to take it out of your hands, I hope you didn't put too much time into it yet?

**Comment by leafac** [comment]
I actually haven’t had the time to work on this at all. Thank you for taking it out of my hands 😃
