### ISSUE TITLE
Release failed: `pika: not found`

### ISSUE THREAD

**Issue by oscard0m** [octokit/plugin-retry.js#321]
You can find details here: https://github.com/octokit/plugin-retry.js/runs/7048993516?check_suite_focus=true

Context: https://github.com/octokit/core.js/pull/454

**Comment by wolfy1339** [comment]
A simple octoherd script to fix this would help

**Comment by oscard0m** [comment]
> A simple octoherd script to fix this would help

Yep, you are right. I will go for it.

**Comment by wolfy1339** [comment]
Hi @oscard0m,

Can you check the octokit repos again? I think you may have missed some

**Comment by oscard0m** [comment]
> I think it's all of them that were changed over, but best to double check

I just run a search and no occurrences left for `"pika pack"`:
https://github.com/search?q=org%3Aoctokit+%22pika+build%22&type=code

So I assume this has been solved
