### ISSUE TITLE
[BUG]: last commit was detected as a fix instead of breaking change (node version)

### ISSUE THREAD

**Issue by existe-deja** [octokit/plugin-retry.js#431]
### What happened?

the package isn't supporting node >= 16 so I can't install my project. This is because of BREAKING CHANGE of [this commit](https://github.com/octokit/plugin-retry.js/commit/52cf451c23b82898046f861b5806915e93561f98) wasn't detected

### Versions

@octokit/plugin-retry@4.1.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidzwa** [comment]
Example reproduction where I encounter the same issue:
https://github.com/fdm-monster/fdm-monster/pull/1861

**Comment by wolfy1339** [comment]
You linked to the wrong commit.

Those changes weren't meant to be breaking. It was only supposed to change the build system.

Feel free to send a PR if you would like to. I don't have time to get around to this soon

**Comment by benmvp** [comment]
It's this commit: https://github.com/octokit/plugin-retry.js/blame/main/package.json#L85

**Comment by benmvp** [comment]
Here's a PR for the fix: https://github.com/octokit/plugin-retry.js/pull/432
