### ISSUE TITLE
Incorrect code in release notes

### ISSUE THREAD

**Issue by Piccirello** [octokit/plugin-retry.js#44]
The release notes for v3.0.0 list a breaking change in how this plugin is exported. There's a typo in the breaking change description, leading to an error when used. The exported function is named `retry`, not `retryPlugin`.

Before: `const { retryPlugin } = require("@octokit/plugin-retry")`

After: `const { retry } = require("@octokit/plugin-retry")`

**Comment by gr2m** [comment]
Ohh thank you so much Tom, I'll fix that right away. Sorry for the trouble this caused you!
