### ISSUE TITLE
Build Fails with 3.0.0

### ISSUE THREAD

**Issue by hipstersmoothie** [octokit/plugin-retry.js#45]
An import from `@octokit/core` makes it into the .d.ts files but isn't listed as a dependency.

![Screen Shot 2020-01-27 at 9 10 54 AM](https://user-images.githubusercontent.com/1192452/73196733-f8da5200-40e4-11ea-9e7d-503a4c8447c8.png)

**Comment by hipstersmoothie** [comment]
closing per https://github.com/octokit/plugin-throttling.js/issues/127#issuecomment-576792811

**Comment by gr2m** [comment]
I will add a note to the README for the time being.
