### ISSUE TITLE
[FEAT]: Retry on GraphQL Request with Multiple Mutiations (Partial Data) Should Only Retry Failed Mutations

### ISSUE THREAD

**Issue by MarkusMit** [octokit/plugin-retry.js#489]
### Describe the need

If I have a GraphQL request with multiple mutations (using aliases), and some of the mutations succeed, and others produce (retryable) errors, then octokit should store the data from the successful mutations (Partial Data), and remove those already successfully executed mutations from the next "retry-request." 
Then after the final retry, that stored data of earlier successful mutations should be added again to the response/error object returned to the client.

### API Version

GraphQL, Enterprise Server 3.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
That is retry logic that goes beyond the scope of this plugin. It sure would be cool to have a more advanced GraphQL-specific retry plugin though. I don't see us adding that to this plugin, it's focused on request retries.
