### ISSUE TITLE
[BUG]: Error ERR_MODULE_NOT_FOUND in v7

### ISSUE THREAD

**Issue by AnnAngela** [octokit/plugin-retry.js#519]
### What happened?

Minimal reproduction environment: https://github.com/AnnAngela/octokit-esm-bug

When [importing `@octokit/plugin-retry`@7](https://github.com/AnnAngela/octokit-esm-bug/blob/671d13001be6532f5ab518924aeaa80400a8928a/octokit.js#L1), there is an error: <https://github.com/AnnAngela/octokit-esm-bug/actions/runs/8042420281/job/21963054016#step:5:11>

And I tested to [import the `bottleneck/light`](https://github.com/AnnAngela/octokit-esm-bug/blob/671d13001be6532f5ab518924aeaa80400a8928a/bottleneck_light-bug.js#L1) like this:

<https://github.com/octokit/plugin-retry.js/blob/60e9ac265cc36ba6f896e76e1a2c871ea7d0682b/src/wrap-request.ts#L2>

The error is still happened: <https://github.com/AnnAngela/octokit-esm-bug/actions/runs/8042420281/job/21963054016#step:6:11>

When I tried to [import the `bottleneck/light` with `.js` extension](https://github.com/AnnAngela/octokit-esm-bug/blob/671d13001be6532f5ab518924aeaa80400a8928a/bottleneck_light-good.js#L1), no error anymore: <https://github.com/AnnAngela/octokit-esm-bug/actions/runs/8042420281/job/21963054016#step:7:7>

### Versions

@octokit/plugin-retry: 7.0.0

Node 20.11.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This bug was hidden because of a `// @ts-expect-error`, because there are no types for bottleneck/light in the published version on npm

This is certainly a great catch
