### ISSUE TITLE
[BUG]: `Cannot construct a Request with a Request object that has already been used.`

### ISSUE THREAD

**Issue by jakub-g** [octokit/plugin-retry.js#543]
### What happened?

Today GitHub had an outage (related: https://github.com/octokit/plugin-retry.js/issues/2) and the API was replying with 500s.

Due to this, the retry plugin has been retrying failed requests in our CI, but those retries were failing with `Cannot construct a Request with a Request object that has already been used.`.

### Versions

octokit-request 8.1.4
octokit-plugin-retry 6.0.1
node 20.10.0

### Relevant log output

```
<path-to-repo>/.yarn/__virtual__/@octokit-plugin-retry-virtual-913e8d7a91/0/cache/@octokit-plugin-retry-npm-6.0.1-b38996e6ff-2f5cd8b221.zip/node_modules/@octokit/plugin-retry/dist-node/index.js:71
  const response = await request(request, options);
                   ^
RequestError [HttpError]: Cannot construct a Request with a Request object that has already been used.
    at <path-to-repo>/.yarn/cache/@octokit-request-npm-8.1.4-e871d5ebf1-a51470f470.zip/node_modules/@octokit/request/dist-node/index.js:144:11
    at async requestWithGraphqlErrorHandling (<path-to-repo>/.yarn/__virtual__/@octokit-plugin-retry-virtual-913e8d7a91/0/cache/@octokit-plugin-retry-npm-6.0.1-b38996e6ff-2f5cd8b221.zip/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (<path-to-repo>/.yarn/cache/bottleneck-npm-2.19.5-2c6092aa17-084e33d97e.zip/node_modules/bottleneck/light.js:405:18) {
  status: 500,
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/<org>/<repo>/issues/comments/<id>',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.2 octokit-core.js/5.0.1 Node.js/20.10.0 (linux; arm64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
```

The underlying error comes from undici (which is nodejs built-in `fetch` impl) which is used by `octokit/request`:

- https://github.com/nodejs/undici/blob/ad811224c63c99d6840475f9805ea6dbe8be7747/lib/web/fetch/request.js#L542

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
Could you share a minimal reproducible test case please? I've haven't seen this error before, and I have plenty of request retries across my projects, many of which use latest octokit with the native fetch from unidici

**Comment by jakub-g** [comment]
@gr2m Thanks for replying - we just realized this is coming from a regression in the [dd-trace](https://github.com/DataDog/dd-trace-js/issues/4259) library. Closing.
